# Copyright cocotb contributors
# Licensed under the Revised BSD License, see LICENSE for details.
# SPDX-License-Identifier: BSD-3-Clause

# content has moved to Makefile.riviera
include $(shell cocotb-config --makefiles)/simulators/Makefile.riviera
